// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TWTodos.Data;

#nullable disable

namespace CajuTalkAPI.Data.MigrationsPostgres
{
    [DbContext(typeof(CajuTalkContext))]
    partial class CajuTalkContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("CajuTalk")
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TWTodos.Models.Mensagem", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("Conteudo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DataEnvio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ID_Sala")
                        .HasColumnType("integer");

                    b.Property<int>("ID_Usuario")
                        .HasColumnType("integer");

                    b.Property<string>("TipoMensagem")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("Mensagem", "CajuTalk");
                });

            modelBuilder.Entity("TWTodos.Models.RefreshToken", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Expires")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Revoked")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UsuarioId");

                    b.ToTable("RefreshToken", "CajuTalk");
                });

            modelBuilder.Entity("TWTodos.Models.SalaChat", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int>("CriadorID")
                        .HasColumnType("integer");

                    b.Property<string>("FotoPerfilURL")
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Publica")
                        .HasColumnType("boolean");

                    b.Property<string>("Senha")
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("SalaChat", "CajuTalk");
                });

            modelBuilder.Entity("TWTodos.Models.Usuario", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("CorFundo")
                        .HasColumnType("text");

                    b.Property<string>("FotoPerfilURL")
                        .HasColumnType("text");

                    b.Property<string>("LoginUsuario")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NomeUsuario")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Recado")
                        .HasColumnType("text");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("Usuario", "CajuTalk");
                });

            modelBuilder.Entity("TWTodos.Models.UsuarioSala", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<bool>("Criador")
                        .HasColumnType("boolean");

                    b.Property<int>("ID_Sala")
                        .HasColumnType("integer");

                    b.Property<int>("ID_Usuario")
                        .HasColumnType("integer");

                    b.Property<bool>("UsuarioBanido")
                        .HasColumnType("boolean");

                    b.HasKey("ID");

                    b.HasIndex("ID_Usuario", "ID_Sala")
                        .IsUnique();

                    b.ToTable("Usuario_Sala", "CajuTalk");
                });

            modelBuilder.Entity("TWTodos.Models.RefreshToken", b =>
                {
                    b.HasOne("TWTodos.Models.Usuario", "Usuario")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("TWTodos.Models.Usuario", b =>
                {
                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
